export default {
  IMG1: require('@assets/img1.jpeg'),
  IMG2: require('@assets/img2.jpeg'),
  IMG3: require('@assets/img3.jpeg'),
  IMG4: require('@assets/img4.jpeg'),
  IMG5: require('@assets/img5.jpeg'),
  IMG6: require('@assets/img6.jpeg'),
  IMG7: require('@assets/img7.jpeg'),
  IMG8: require('@assets/img8.jpeg'),
  IMG9: require('@assets/img9.jpeg'),
  IMG10: require('@assets/img10.jpeg'),
  IMG11: require('@assets/img11.jpeg'),
  IMG12: require('@assets/img12.jpeg'),
  IMG13: require('@assets/img13.jpeg'),
  IMG14: require('@assets/img14.jpeg'),
  IMG15: require('@assets/img15.jpeg'),
  IMG16: require('@assets/img16.jpeg'),
  CART_ICON: require('@assets/cart.png'),
  CLOSE_ICON: require('@assets/close.png'),
  BACK_ICON: require('@assets/backArrow.png'),
  INR_ICON: require('@assets/india_1.png'),
};
